
-- 10 게시글
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Mauris sit amet eros.', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Red', 'Gilda', 'Bess', '2024-03-26 02:15:02', '2023-11-05 01:21:53');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Curabitur convallis.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Pink', 'Cinnamon', 'Oren', '2023-08-19 18:29:29', '2023-06-20 09:27:31');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Donec semper sapien a libero.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', null, 'Caresse', 'Janaya', '2024-02-27 07:00:51', '2024-01-19 13:23:27');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', null, 'Christabella', 'Wilt', '2024-04-08 09:46:45', '2024-02-11 02:34:32');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Integer a nibh.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Fuscia', 'Coriss', 'Tucker', '2023-10-11 13:25:57', '2023-06-22 04:43:56');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Suspendisse potenti.', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Khaki', 'Lauryn', 'Rufus', '2023-08-22 10:25:33', '2023-09-23 12:00:16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nullam molestie nibh in lectus.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Crimson', 'Tobi', 'Goraud', '2024-02-22 21:55:14', '2023-10-07 02:56:34');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Aliquam quis turpis eget elit sodales scelerisque.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Indigo', 'Marcille', 'Moria', '2024-02-22 01:51:16', '2024-05-19 00:58:02');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('In sagittis dui vel nisl.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Indigo', 'Chiarra', 'Rancell', '2023-10-06 04:13:35', '2024-03-20 18:53:48');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Duis at velit eu est congue elementum.', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', null, 'Joshuah', 'Vinnie', '2023-10-18 05:10:10', '2024-03-13 20:37:52');
